"""Generate a presentable README.md for the solutions repo from the solve log.

Rebuilt on every submission so it always reflects the full history: a header
with summary badges, per-difficulty counts, and a reverse-chronological table
of every solved problem with its topic and whether it was solved optimally.
"""

from __future__ import annotations

from typing import Any

_DIFF_ORDER = {"easy": 0, "medium": 1, "hard": 2}
_APPROACH = {"optimal": "Optimal", "suboptimal": "Suboptimal"}


def _badge(label: str, value: str, color: str) -> str:
    def enc(s: str) -> str:
        return (s.replace("-", "--").replace("_", "__")
                .replace("/", "%2F").replace(" ", "%20"))
    return f"![{label}](https://img.shields.io/badge/{enc(label)}-{enc(value)}-{color})"


def generate(entries: list[dict[str, Any]], streak: int = 0) -> str:
    total = len(entries)
    by_diff = {"easy": 0, "medium": 0, "hard": 0}
    optimal = suboptimal = 0
    for e in entries:
        by_diff[e.get("difficulty", "")] = by_diff.get(e.get("difficulty", ""), 0) + 1
        opt = e.get("optimality")
        if opt == "optimal":
            optimal += 1
        elif opt == "suboptimal":
            suboptimal += 1

    graded = optimal + suboptimal
    lines: list[str] = []
    lines.append("# LeetCode Solutions")
    lines.append("")
    badges = [
        _badge("Solved", str(total), "1f6feb"),
        _badge("Streak", f"{streak} days", "f59e0b"),
        _badge("Easy", str(by_diff["easy"]), "1a7f37"),
        _badge("Medium", str(by_diff["medium"]), "9a6700"),
        _badge("Hard", str(by_diff["hard"]), "cf222e"),
    ]
    if graded:
        badges.append(_badge("Optimal", f"{optimal}/{graded}", "2f6feb"))
    lines.append(" ".join(badges))
    lines.append("")
    lines.append("Auto-generated log of my LeetCode solutions. "
                 "Updated automatically on every submission.")
    lines.append("")

    if graded:
        pct = round(100 * optimal / graded)
        lines.append(f"**Solved optimally:** {optimal}/{graded} ({pct}%)  -  "
                     f"flagged as brute-force/suboptimal: {suboptimal}")
        lines.append("")

    # Table, most recent first.
    ordered = sorted(
        entries,
        key=lambda e: (e.get("date", ""), e.get("number", 0)),
        reverse=True,
    )
    lines.append("## Log")
    lines.append("")
    lines.append("| Date | # | Problem | Difficulty | Topic | Approach |")
    lines.append("|------|---|---------|------------|-------|----------|")
    for e in ordered:
        url = e.get("url") or f"https://leetcode.com/problems/{e.get('slug','')}/"
        title = e.get("title", e.get("slug", "?"))
        diff = (e.get("difficulty", "") or "").capitalize() or "-"
        topic = e.get("topic") or "-"
        approach = _APPROACH.get(e.get("optimality", ""), "-")
        lines.append(f"| {e.get('date','')} | {e.get('number','')} | "
                     f"[{title}]({url}) | {diff} | {topic} | {approach} |")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by [leetcode-assistant](https://github.com/TomShephard/"
                 "leetcode-assistant).*")
    lines.append("")
    return "\n".join(lines)
