"""Generate the app icon with no third-party deps.

Produces, in leetcode_cli/:
  icon.png        64x64 PNG (used for PyInstaller and previews)
  icon.ico        multi-size BMP-based ICO (16/32/48/64) -- what Windows
                  title bars want; PNG-encoded ICOs often don't render small
  _icondata.py    base64 of both, so the GUI can set its window icon WITHOUT
                  depending on a bundled file being found at runtime (the
                  frozen-exe failure mode)

Re-run:  py tools/make_icon.py
"""

from __future__ import annotations

import base64
import struct
import zlib
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent.parent / "leetcode_cli"
BG = (47, 111, 235)        # accent blue
CHECK = (255, 255, 255)
SIZES = [16, 32, 48, 64]


def _dist_point_seg(px, py, x1, y1, x2, y2):
    dx, dy = x2 - x1, y2 - y1
    if dx == 0 and dy == 0:
        return ((px - x1) ** 2 + (py - y1) ** 2) ** 0.5
    t = ((px - x1) * dx + (py - y1) * dy) / (dx * dx + dy * dy)
    t = max(0.0, min(1.0, t))
    cx, cy = x1 + t * dx, y1 + t * dy
    return ((px - cx) ** 2 + (py - cy) ** 2) ** 0.5


def _in_rounded_rect(x, y, w, h, r, margin):
    x0, y0, x1, y1 = margin, margin, w - 1 - margin, h - 1 - margin
    if x < x0 or x > x1 or y < y0 or y > y1:
        return False
    cx = min(max(x, x0 + r), x1 - r)
    cy = min(max(y, y0 + r), y1 - r)
    return (x - cx) ** 2 + (y - cy) ** 2 <= r * r


def render(size: int):
    s = size / 64.0
    seg = [(15 * s, 34 * s, 27 * s, 46 * s), (27 * s, 46 * s, 49 * s, 19 * s)]
    thick = max(1.4, 5.2 * s)
    r = max(2, round(14 * s))
    margin = max(1, round(4 * s))
    rows = []
    for y in range(size):
        row = []
        for x in range(size):
            inside = _in_rounded_rect(x, y, size, size, r, margin)
            on_check = any(_dist_point_seg(x, y, *sg) <= thick for sg in seg)
            if inside and on_check:
                row.append((*CHECK, 255))
            elif inside:
                row.append((*BG, 255))
            else:
                row.append((0, 0, 0, 0))
        rows.append(row)
    return rows


# ---- PNG ----
def _png_chunk(tag: bytes, data: bytes) -> bytes:
    return (struct.pack(">I", len(data)) + tag + data +
            struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))


def encode_png(rows) -> bytes:
    h, w = len(rows), len(rows[0])
    raw = bytearray()
    for row in rows:
        raw.append(0)
        for (r, g, b, a) in row:
            raw += bytes((r, g, b, a))
    return (b"\x89PNG\r\n\x1a\n" +
            _png_chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0)) +
            _png_chunk(b"IDAT", zlib.compress(bytes(raw), 9)) +
            _png_chunk(b"IEND", b""))


# ---- BMP-based ICO ----
def _bmp_image(rows) -> bytes:
    h, w = len(rows), len(rows[0])
    header = struct.pack("<IiiHHIIiiII", 40, w, h * 2, 1, 32, 0, 0, 0, 0, 0, 0)
    xor = bytearray()
    for y in range(h - 1, -1, -1):           # bottom-up, BGRA
        for (r, g, b, a) in rows[y]:
            xor += bytes((b, g, r, a))
    and_row = ((w + 31) // 32) * 4            # 1bpp mask, padded; all zero
    andmask = b"\x00" * (and_row * h)
    return header + bytes(xor) + andmask


def build_ico(sizes) -> bytes:
    images = [_bmp_image(render(s)) for s in sizes]
    icondir = struct.pack("<HHH", 0, 1, len(images))
    entries = bytearray()
    offset = 6 + 16 * len(images)
    for s, img in zip(sizes, images):
        wb = s if s < 256 else 0
        entries += struct.pack("<BBBBHHII", wb, wb, 0, 0, 1, 32, len(img), offset)
        offset += len(img)
    return icondir + bytes(entries) + b"".join(images)


def main() -> int:
    png = encode_png(render(64))
    ico = build_ico(SIZES)
    (OUT_DIR / "icon.png").write_bytes(png)
    (OUT_DIR / "icon.ico").write_bytes(ico)
    data_py = (
        '"""Auto-generated by tools/make_icon.py -- do not edit."""\n\n'
        f'PNG_B64 = "{base64.b64encode(png).decode()}"\n\n'
        f'ICO_B64 = "{base64.b64encode(ico).decode()}"\n'
    )
    (OUT_DIR / "_icondata.py").write_text(data_py, encoding="utf-8")
    print(f"icon.png {len(png)}B, icon.ico {len(ico)}B ({len(SIZES)} sizes), "
          f"_icondata.py written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
